### ISSUE TITLE
1.5.3 User Name and Password Incorrect

### ISSUE THREAD

**Issue by 3DNut** [FaisalUmair/udemy-downloader-gui#105]
I tried to login in with 1.5.3 and got the familiar login issue.

**Comment by FaisalUmair** [comment]
Hello @3DNut Wait for some time and login again. Do not logout if you don't need to. Keep the session active to minimise the number of login requests.

**Comment by 1Busayo** [comment]
i cant login 


![cudeapture](https://user-images.githubusercontent.com/35940016/40574114-e405c5dc-60c4-11e8-83cd-1bf19164615b.PNG)

**Comment by 3DNut** [comment]
I waited 24 hours and same thing. I haven't ever had a successful login in the past 3 revisions.

**Comment by jimmy8646** [comment]
Same issue here version:1.5.3

**Comment by FaisalUmair** [comment]
I am working on a proper/permanent fix for this. I think the login should work fine after that.

**Comment by caneto** [comment]
Not Work, not login, verision 1.53...

**Comment by AyaskantaIBM** [comment]
I am again facing same login issues. Could you please help with.

**Comment by abuvanth** [comment]
same issue

**Comment by Bionic31** [comment]
sir looks like the same issue has aroused again 

keep us update when it's fixed, please
Thanks

**Comment by prakass1** [comment]
@FaisalUmair looks the issue is still there.

Keep us posted on the fix.

Thanks

**Comment by FaisalUmair** [comment]
Yes @prakass1 I am uploading the new version.

**Comment by FaisalUmair** [comment]
This issue has been fixed in v1.5.4. Download and provide feedback.

**Comment by suksin** [comment]
@FaisalUmair Wondering if this works with Single Sign-on Udemy for Business?

**Comment by lrdeoliveira** [comment]
download error, not low. Login but not download

**Comment by Bionic31** [comment]
thanks for new feature you add

**Comment by FaisalUmair** [comment]
@suksin Good point. I think it would be safe for us to make `www` dynamic and replace it with business subdomain for login also. 

But if anyone here has a business account they can check if the login is working for them. Then we can deal with it accordingly.

**Comment by FaisalUmair** [comment]
@Bionic31 No, I am a Student.

**Comment by lucianene** [comment]
@FaisalUmair thanks dude, you are awesome!

**Comment by Bionic31** [comment]
do you have any course on angular 6 or 5

**Comment by 1Busayo** [comment]
Version 1.5.4 is working fine

**Comment by FaisalUmair** [comment]
@Bionic31 Do you mean if I can suggest any course on AngularJS?

**Comment by Bionic31** [comment]
yea one i can download

**Comment by Bionic31** [comment]
any
