### ISSUE TITLE
Attachments Not Downloading

### ISSUE THREAD

**Issue by vikasnewports** [FaisalUmair/udemy-downloader-gui#12]
Hello
first of all i am not going for Fork cause I can not contribute.
I have request to add more features like downloading all types of attachments 
I hope this request will be consider for futures updates

**Comment by FaisalUmair** [comment]
Hi, 

Yes, The ability to download attachments is missing for now. But I am already working on a new update which will allow attachment downloads along with some bug fixes.

Thanks

**Comment by FaisalUmair** [comment]
Support for downloading attachments has been added in v1.3.0. Download [latest](https://github.com/FaisalUmair/udemy-downloader-gui/releases/latest) version.

**Comment by a5h0kkum4r** [comment]
Attachments are not downloaded now and it hangs.

![image](https://user-images.githubusercontent.com/61622687/75607655-6a138780-5b1f-11ea-926f-582cb1b0ae7e.png)

**Comment by ioadejuwon** [comment]
I have this issue too
