### ISSUE TITLE
unable to log in again same issue

### ISSUE THREAD

**Issue by nikhil7451** [FaisalUmair/udemy-downloader-gui#128]
please fix this Faisal Bhai unable to login incorrect password or email issue

**Comment by FaisalUmair** [comment]
Appears to work fine for me, what versions are you using? v 1.6.0 is the latest version.

**Comment by nikhil7451** [comment]
sorry it's working,  I used an earlier version mistakenly

**Comment by nikhil7451** [comment]
thanks for the help
