### ISSUE TITLE
Course show Limit

### ISSUE THREAD

**Issue by passarante** [FaisalUmair/udemy-downloader-gui#13]
Hi, thanks four life saving program :)
My, issue is program showing only last added 100 course and other courses not shown 
also there be  a search course options :)

**Comment by FaisalUmair** [comment]
Hi, Course search option is a good idea. I will definitely work on that. 

And for the issue where only 100 courses are displayed, I would have to subscribe to more than 100 courses to debug it. I will probably enroll in free courses temporarily to have more than 100 subscribed courses.

**Comment by passarante** [comment]
Thanks for fast answer and preciate to my opinion
Kind Regards
Guney Dirim


Kimden: Faisal Umair
Gönderilme: 25 Aralık 2017 Pazartesi 20:28
Kime: FaisalUmair/udemy-downloader-gui
Bilgi: passarante; Author
Konu: Re: [FaisalUmair/udemy-downloader-gui] Course show Limit (#13)

Hi, Course search option is a good idea. I will definitely work on that.
And for the issue where only 100 courses are displayed, I would have to subscribe to more than 100 courses to debug it. I will probably enroll in free courses temporarily to have more than 100 subscribed courses.

**Comment by vikasnewports** [comment]
one more idea from my side is that
Enable the user to extract/export the list of subscribed courses name with url to manage his/her portfoli

**Comment by FaisalUmair** [comment]
Sorry I don't think it is clear to me. What do you mean by managing portfolio?

**Comment by vikasnewports** [comment]
Portfolio = Category
What if we would able to export the list of subscribed courses in below format
Name of Course | URL of Course | Course Category
it is most simplest from my end 
I hope it would give you more clear idea about my suggestion

**Comment by FaisalUmair** [comment]
Ok, but how would it help someone?

**Comment by vikasnewports** [comment]
it will help me to to manage my data
if its not appropriate then you can skip it

**Comment by FaisalUmair** [comment]
Well I respect your opinion but I don't think its something that most users would need. 

What I think is a good idea though is to add option to export download links so that the users can download videos through any external download manager. Let me know what you think about that.

**Comment by vikasnewports** [comment]
I agree with your view that most of the users does not care about it
yes exporting downloadable links is a good it would need a access token for external download managers
but it would save can someone decode it ?

**Comment by FaisalUmair** [comment]
The download links would have access token in the url as a parameter. Users can simply import the link in the download manager.

**Comment by vikasnewports** [comment]
yes thank you for this feature too

**Comment by FaisalUmair** [comment]
This issue has been fixed. Download [latest](https://github.com/FaisalUmair/udemy-downloader-gui/releases/latest) version.
