### ISSUE TITLE
How to do install this software in ubuntu ?

### ISSUE THREAD

**Issue by dougs007** [FaisalUmair/udemy-downloader-gui#130]

**Comment by dougs007** [comment]
Hi guys, someone help`s me ?

**Comment by papujarapy** [comment]
firt step
**uname -m** 
you console, give permission to execute
**chmod +x Udeler*.appimage**
we only install the application with
**sudo ./Udeler*.appimage**

**Comment by dougs007** [comment]
Ok, thanks guys, I got it. I'll close this issue

**Comment by kamau-mbugua** [comment]
[Download Here](https://github.com/FaisalUmair/udemy-downloader-gui/releases)

- extract it in your download area.
- click on it and open with terminal. or just Ctrl+Alt+T.
- chmod +x Udeler-1.8.0-linux-x86_x64.AppImage
- sudo ./Udeler-1.8.0-linux-x86_x64.AppImage

**Comment by guptamrshashank** [comment]
> Hi dougs007,
> you can
> 1-Download last version from here:
> https://github.com/FaisalUmair/udemy-downloader-gui/releases
> 2-Give permissions to execute: open a terminal and
> cd fullPathToDownloadedApp
> chmod +x Udeler-1.6.2-linux-x86_x64.AppImage
> 3-Execute with
> sudo ./Udeler-1.6.2-linux-x86_x64.AppImage
> 
> There are several blogs about this, so if you need it, so google can help you (install udeler ubuntu 16.04)
> Kind regards

Works, Thanks so much

**Comment by Ciilka** [comment]
Download latest  https://github.com/FaisalUmair/udemy-downloader-gui/releases
Make an executable by using `chmod +x Udeler-1.8.2-linux-x86_x64.AppImage ` 
execute ` ./Udeler-1.8.2-linux-x86_x64.AppImage `
have a nice day
