### ISSUE TITLE
Download stuck at "Building Course Data"

### ISSUE THREAD

**Issue by DragoonHP** [FaisalUmair/udemy-downloader-gui#146]

**Comment by FaisalUmair** [comment]
Refer to #145 and please check for duplicate issues before creating one.

**Comment by Happyrajsinh** [comment]
Getting same error. Even for the course which I downloaded earlier using Udeler only! I did all possible combination of settings with skip attachments, subtitles and auto retry on error. Same account I used on  both occasion which is a business account.
Any help on this will be appreciated.

Udeler Version : 1.8.2-windows-x64
Course name: Create a Battle Royale game using Unreal Engine 4 Blueprints

**Comment by vishw33** [comment]
@Happyrajsinh  same with me too , but I am using Mac

**Comment by Happyrajsinh** [comment]
@vishw33 even I tried on my mac but its a native app so error should be same for both platforms.

**Comment by Happyrajsinh** [comment]
But if it's urgent one can find the same course for download on archive.org .

**Comment by chuksdsilent** [comment]
I am having the same error

**Comment by yomoko** [comment]
same here, some courses ok, some course with this error. why is that?

**Comment by eveshino** [comment]
im having the same issue

**Comment by mgmTechnology** [comment]
me to.. 
hangs. not on all, but on some courses

**Comment by girishkdesh** [comment]
Me too
![Screenshot 2021-05-15 100110](https://user-images.githubusercontent.com/29687434/118347946-87861300-b564-11eb-8a82-6de25103b131.png)

**Comment by shyamkrisharry** [comment]
It's getting stuck for me too 😞 seems like udemy has made their videos as mp4 chunks now that we aren't able to download those.

**Comment by bhargavbattula** [comment]
I too having the same issue

**Comment by fazzy12** [comment]
no solution yet?

**Comment by shehuawwal** [comment]
I have been having this issue as well,

**Comment by hmnshsinghal** [comment]
getting same error caurse stuck at building caurse data

**Comment by badrelmazaz** [comment]
Same issue

**Comment by dhannjayyy** [comment]
Same issue on a particular course.

**Comment by RishiKumar158** [comment]
same issue till now!!
