### ISSUE TITLE
Only Five Video Download On My Purchased Course

### ISSUE THREAD

**Issue by phytondesc** [FaisalUmair/udemy-downloader-gui#153]
I tried different courses for download but cant download after five video.

**Comment by FaisalUmair** [comment]
What version of Udeler are you using?

**Comment by phytondesc** [comment]
Latest version , 1.6.2.

I've used it before and downloaded it.

**Comment by phytondesc** [comment]
You can see problem in action.
Always find 5 Item every course.
https://youtu.be/NvDS_plMbyI

**Comment by FaisalUmair** [comment]
Thanks for sharing the video. It made things clear.

You need to turn off 'Enable Download Start/End' in the settings, as per your current settings it will only download 5 lectures. From lecture 2 to lecture 6.

**Comment by phytondesc** [comment]
Sorry,
I miss that options. Its ok now.

Thank you
