### ISSUE TITLE
Auto Refresh 

### ISSUE THREAD

**Issue by 1871vinayak** [FaisalUmair/udemy-downloader-gui#155]
The app should auto refresh every 30 sec or 1 min for any new content added to the account.

**Comment by FaisalUmair** [comment]
Well, I think we don't buy new courses that often. Auto-refreshing every 30 seconds would be overkill for just loading new courses. However, adding a button to refresh the application could be considered. 

But for now, the user can simply leave the `search field` empty and press `enter`, this will force the application to reload the courses. You also have the options to restart the application, or logout-login again.
