### ISSUE TITLE
Detect already downloaded files

### ISSUE THREAD

**Issue by muescha** [FaisalUmair/udemy-downloader-gui#16]
when
- i startet Udeler
- i start a download
- i hit on pause (still downloaded 1,1GB of data)
- i closed Udeler
- i restart the Udeler app
- i start to download the course again

what i see
- the download starts with 1 of 448 items (just now it looks like it starts the download from the beginning)

what i expected
- it should remember (detect) which courses already downloaded (in half?)

**Comment by FaisalUmair** [comment]
Yeah, I am aware of this and the retry option was implemented in a way that it starts downloading from beginning because I knew that at some point in future I will be implementing the feature to resume broken download which will if will resume from beginning it will detect that the files are already downloaded 100% and then resume from the file which it detects to be broken.

**Comment by muescha** [comment]
if a file is broken while downloading it has a temporary extension. so just look for the filename before downloading: if it exists, then skip the download process.

(only problem maybe if the lectures are the same name and with same number)

**Comment by FaisalUmair** [comment]
Well, I think if I try to resume all. It will automatically skip the ones which are fully downloaded. So there should be no extra work involved in this. If the files is already download when it tries to resume it, the progress will automatically increase as it will take some mili seconds to resume the file as the file is already downloaded so it will automatically reach to the point where it stopped.

**Comment by muescha** [comment]
ok - understand - it check it by checksum and not by filename then?

**Comment by FaisalUmair** [comment]
If the user changed any setting and tries to download we can download from beginning in that case.


And for resuming by file, I am using a third party nodejs package. So I am not aware what it checks, but I know if we throw a fully downloaded file at it to resume it will just skip it. I think most likely it could be checking for temporary download file and if it doesn't find it it skips it. My point here was to bring forward the fact that I don't have to check for it manually I just try to resume and it should skip it automatically.

**Comment by ejose19** [comment]
Hello, thanks for your amazing program. Do you plan on implementing this soon? My udeler failed at half the course and this is very big course (10GB) my internet is really slow, so starting again would take me weeks to complete.

**Comment by FaisalUmair** [comment]
Hi @ejose19 , I am sorry about the download issues. I know it doesn't work very well. I was actually looking for an alternative implementation for downloading files. But I guess we will stick to this for some time and implement the resume from broken downloads for now. 

I will update the application in few days.

Thank you.

**Comment by ashaqhussain** [comment]
When can we expect an update with resume feature..plz

**Comment by FaisalUmair** [comment]
Hello @ashaqhussain , I am Sorry that I haven't been able to catch up with the issues here. I am busy with some other projects. But I will make sure that I will at least fix all the issues related to downloading course lectures. Expect an update this week.

**Comment by agentak123** [comment]
when will u update
waiting for this update 🙄

**Comment by agentak123** [comment]
8 days gone.. u said in a week u will release an update 😁

**Comment by FaisalUmair** [comment]
Hello @agentak123 , I am Sorry for the delay. But I am very busy with some other projects which are on a deadline. I am unable to get any free time these days otherwise I would have fixed this already.

**Comment by FaisalUmair** [comment]
Hello everyone, I have added the feature which will detect already downloaded files and resume from where it stopped last time. I am currently testing it on various platforms. The changes have already been committed, if you want to try it, clone the repo. 

I will pack and release the app soon (probably tomorrow). And I am sorry for the delay. 

Thanks.

**Comment by ashaqhussain** [comment]
Waiting.... Sigh

**Comment by FaisalUmair** [comment]
Please download the latest version from [here](https://github.com/FaisalUmair/udemy-downloader-gui/releases/latest)  and let me know if the problem has been resolved.

Thanks

**Comment by agentak123** [comment]
finally thanks mate

**Comment by sha1sum** [comment]
I was looking for issues that maybe I could resolve by contributing to the project, and was disheartened to see people posting impatient messages. This is open source software, and most people have actual lives that take priority over these types of projects (and frankly, your use of them as well). If you're unhappy with the wait, learn to code and contribute! Otherwise, be grateful to the creator for making this free for all of you to use.

Thank you, @FaisalUmair !

**Comment by asmechergui** [comment]
thank you @FaisalUmair

**Comment by Jassi10** [comment]
This is just amazing, thanks @FaisalUmair for the software and your support.
The download had stopped and I was searching for the resolution and found here to delete the .mtd file.
Thanks again,Keep up the good work

**Comment by adiawk** [comment]
i just accidently fix this problem. I delete the latest file (Its maybe broken file or corrupt), and then i redownload the course, and its resuming from the file that i delete

**Comment by danison2** [comment]
@adiawk Yes, that works. Anyone having the issue can delete the incomplete .MTD file.

**Comment by PembaTamang** [comment]
I am using the latest version 1.8.2. I download a course while pausing and resuming and after it was done I found that the zip is corrupted.. Please help
