### ISSUE TITLE
Web

### ISSUE THREAD

**Issue by kinb98** [FaisalUmair/udemy-downloader-gui#173]
Why is udeler web not working ?
Chrome says udeler web refused to connect.

**Comment by FaisalUmair** [comment]
There was some issue with the server. Check now, it should be working.

**Comment by Nirose** [comment]
is the login information sent to the server or how does this work?

**Comment by FaisalUmair** [comment]
The login information is indirectly sent to the Udemy server. I am proxying the request through another server, and the reason to do that is chrome is preventing the use of cross-origin request.

**Comment by Nirose** [comment]
thanks for the explantaion!

-------- Original Message --------
