### ISSUE TITLE
Get stuck at Building Course data

### ISSUE THREAD

**Issue by adrastee** [FaisalUmair/udemy-downloader-gui#174]
Hi,
Trying to use your GUI tool but i get stuck at "Building Course data", even one our after the start.
Thanks for any help.
Version is Udeler v1.6.2

**Comment by FaisalUmair** [comment]
Do you face this issue for only a particular course?

**Comment by adrastee** [comment]
Yes, and I figured out, it does not contain any videos, but only text.
So I guess your tool does not handle that.

**Comment by RahanSharma** [comment]
I am getting same issue however in my case the course do have video lectures. It is getting stuck for specific courses.

**Comment by jatinde** [comment]
Same here. Download get stuck at message Building Course Data. Most likely at videos containing resources as attachment.

**Comment by drout17** [comment]
I am also facing his issue with many courses on Windows to specify I faced the issue for the course

https://www.udemy.com/share/1037KIB0sdcFlaRXw=/
