### ISSUE TITLE
Translation, download path selection and stop/resume

### ISSUE THREAD

**Issue by m4dbra1n** [FaisalUmair/udemy-downloader-gui#2]
Hi,

I'm an Italian user and I've discovered this little piece of bits just today :D 

As from the title I have 3 requests: 
- Italian translation, I can help with that ;)
- Download path selection, to let the user choose where to download the courses
- Stop/resume download, if possible, maybe with external downloader (like wget, curl, etc.)

Thanks and keep up the good work! :D

**Comment by FaisalUmair** [comment]
Hi, welcome to this project and thank you for taking the time to help improve this software. 

As for the progress, I am currently working on the Stop/Pause/Resume functions. I recently upgraded to a new download manager package which allows to pause and resume downloads. However, I have not implemented the pause and resume functionality from the package yet as I wanted to give it a little more time with the basic download to see if it works fine.

I also have some settings to add which include the download path selection. 

Now coming to the Italian translation part, I will surely take your help with that once I finish implementing the pause/resume functionality.

Once again, thank you for your contribution 👍

**Comment by FaisalUmair** [comment]
The Download location option has been added in https://github.com/FaisalUmair/udemy-downloader-gui/commit/ae7b74aeb28d7fce97d405c2a79b12931e2afa3b , will be available in next release
![screen shot 2017-12-06 at 8 56 46 pm](https://user-images.githubusercontent.com/18553256/33670085-2a28bab4-daca-11e7-864f-937f53872c43.png)

**Comment by FaisalUmair** [comment]
I have added the download stop/resume and translation option. 

![pause-resume](https://user-images.githubusercontent.com/18553256/34005414-ccbfed86-e120-11e7-93b7-3a9b71ba7aaf.png)
![language](https://user-images.githubusercontent.com/18553256/34005477-fd22e4ec-e120-11e7-89c9-baf817cafde4.png)


Now for the translation part, if you would like to contribute to Italian translation. Here are the steps to follow:

```
1. Fork this repository.
2. Update the file locale/it.json and add Italian translation to the given English words.
3. Make a pull request.
```

I am planning to release the v1.2.0 with the translation support (at least Italian for now), I can use google translate for this but a human translation would be way better. 

Thanks 👍

**Comment by m4dbra1n** [comment]
OK, I've forked and then made a pull request, but seems to be on my fork of the App, not your main.
Can you kindly check if I did it well, in case?
Sorry for my noobness on GitHub :(

**Comment by FaisalUmair** [comment]
Thanks for the quick response.

I think you have made a pull request to your fork. You do not need to go to the pull request tab. 
On the main page of your fork, you can see a pull request option (where the last commit is displayed). You have to click that option and not the pull request tab on your fork.

**Comment by m4dbra1n** [comment]
OK, I've tried to do a pull request with the file correctly edited directly from your repository, without cloning it.
PS: maybe we could communicate better on Telegram, if you like :)

**Comment by FaisalUmair** [comment]
Yeah that works as well. Thanks 👍  

I don't actually use Telegram or any other Social Networking platform. But you can contact me on my email. I have it displayed on my profile.

**Comment by FaisalUmair** [comment]
The translation works fine. Thanks for contributing. 

So the download path, stop/resume and translation all are implemented. Shall I close this issue now?

**Comment by m4dbra1n** [comment]
All implemented, why not then? ;)
