### ISSUE TITLE
not login

### ISSUE THREAD

**Issue by mahdisky** [FaisalUmair/udemy-downloader-gui#21]
i have account in udemy but not login app
incorrect email/password

**Comment by FaisalUmair** [comment]
Try logging in on udemy.com. Your account might be temporarily blocked due to several incorrect login attempts. However, if you are able to login on udmey.com make sure that there is no pending approval of Terms and Conditions from your side.

**Comment by mahdisky** [comment]
i logging in my account on udemy.com without problem .but i need login with proxy .is this true way?

**Comment by FaisalUmair** [comment]
Well if you logging via a proxy server, check if the same proxy lets you login on udemy.com. If the proxy works and lets you log in on udemy.com then it should be same for the app. But make sure that your internet in configured to use the proxy and not just your web browser.

**Comment by mahdisky** [comment]
yes the proxy works and lets me log  in on udemy but not login with the app. my connection is configured to use the proxy  and true

**Comment by FaisalUmair** [comment]
Did you try using any other account if you have? Try making a new account and see if you are able to login. If not then try disabling the proxy.

**Comment by mahdisky** [comment]
i tried a new account but not login again, i disable the proxy but it doesn't show any error notifications

**Comment by FaisalUmair** [comment]
Ok, so after disabling the proxy make sure you do not have any pending approvals of terms and conditions on udemy.com.

**Comment by mahdisky** [comment]
when the proxy disable cannot open  udemy.com but with the proxy i  can login on udemy . i used Windows x64 ,now what do i do?

**Comment by FaisalUmair** [comment]
Ok, so you are not able to use udemy.com on your network thats why its failing. What country are you in? Try a vpn (maybe Hotspot shield), I guess the proxy isn't applied to the whole network. Just try using a vpn to clear any doubts.

**Comment by mahdisky** [comment]
thnks, i used Hotspot shield and worked,my Previous proxy psiphon than not works
