### ISSUE TITLE
Do not fetch all courses

### ISSUE THREAD

**Issue by AquaCFD** [FaisalUmair/udemy-downloader-gui#22]
Well done, it provides  an easy and smooth help for Udemy's courses downloading. However, there is a tiny issue:

Some of the courses do not appear (For downloading)  in the GUI window.  I have tried many times, in order to upload them, still no luck, though.

**Comment by FaisalUmair** [comment]
Yeah. there is a limit of 100 right now and its not deliberate. It is already registered as a issue #13 

v1.3.0 will take care of this issue.

**Comment by FaisalUmair** [comment]
This has been fixed. Download [latest](https://github.com/FaisalUmair/udemy-downloader-gui/releases/latest) release.
