### ISSUE TITLE
have subtitle ?

### ISSUE THREAD

**Issue by mahdisky** [FaisalUmair/udemy-downloader-gui#23]
is download subtitle courses?

**Comment by FaisalUmair** [comment]
Subtitles are always great. Unfortunately haven't had a chance to work on that. I will try to include that in future releases. 

Thank you.

**Comment by mahdisky** [comment]
thnks

**Comment by FaisalUmair** [comment]
Well keep the issue open until we get this done.

**Comment by mahdisky** [comment]
hi 
when you fix it?

**Comment by FaisalUmair** [comment]
Hi, I am currently working on improving the pause/resume option. It isn't stable as of now. Sometimes the download fails when paused and resumed. The main job of this application is to download Udemy courses and it needs to do that properly. I will surely look into the subtitle feature after we have a stable pause/resume functionality.

**Comment by FaisalUmair** [comment]
Added this option in v1.5.0
