### ISSUE TITLE
log in problem in version 1.6.3 on windows

### ISSUE THREAD

**Issue by q1w2e3r4y6u7i8o9p0** [FaisalUmair/udemy-downloader-gui#233]
even after adding the udeler extension and installing latest version 1.6.3 i am unable to log in. It is just showing awaiting log in request and not  proceeding  any  further. Has somebody got  a  fix to it. If yes, then  pls share
![Screenshot (19)_LI](https://user-images.githubusercontent.com/39621023/54838885-ad4e5f00-4cef-11e9-9ea8-cb901628ccac.jpg)

**Comment by FaisalUmair** [comment]
When it says Awaiting Login Request. You have to log in to Udemy in your web browser, or simply visit Udemy website if already logged in.

**Comment by q1w2e3r4y6u7i8o9p0** [comment]
> When it says Awaiting Login Request. You have to log in to Udemy in your web browser, or simply visit Udemy website if already logged in.

i have already  logged in the udemy account in my web browser

**Comment by FaisalUmair** [comment]
Then you only need to visit Udemy again. Simply open Udemy website when Udeler is saying Awaiting Request

**Comment by q1w2e3r4y6u7i8o9p0** [comment]
> Then you only need to visit Udemy again. Simply open Udemy website when Udeler is saying Awaiting Request

thanks.
