### ISSUE TITLE
Can't login (1.63, Win 10, x64, Chrome Extension installed)

### ISSUE THREAD

**Issue by blankster** [FaisalUmair/udemy-downloader-gui#246]
On Windows 10 (latest patch-level) together with Udeler 1.6.3, I can't login. I've installed the Chrome extension (latest Chrome, Version 73.0.3683.86 (Official Build) (64-bit), deactivated Ublock Origin), but I don't see the anonymous login option (looks like Udeler doesn't recognize it, but the extension recognizes udemy.com and turns from activated to deactivated). I've also watched the Youtube video (https://youtu.be/adhMIaL6i9A ). What I didn't do is to download and build it from source.

![image](https://user-images.githubusercontent.com/1443109/55428566-a0e8c280-5589-11e9-831a-b15af1b89ac6.png)

![image](https://user-images.githubusercontent.com/1443109/55428336-2c158880-5589-11e9-96ee-9bea3cc54b63.png)

![image](https://user-images.githubusercontent.com/1443109/55428392-49e2ed80-5589-11e9-90b9-9efcb81ef1e1.png)

![image](https://user-images.githubusercontent.com/1443109/55428448-697a1600-5589-11e9-80ac-973500111015.png)

Next to this I've also tried https://www.udeler.com/ and changed my password, but nothing helps.

I keep getting "Incorrect Username/Password".

![image](https://user-images.githubusercontent.com/1443109/55428628-c07feb00-5589-11e9-8eed-37f027daa36b.png)

I've no problems login into udemy.com. I thought It's maybe a language problem and even changed udemy.com from German to English - but nothing helps.

I've also tried to uninstall Udeler and reinstall it and tried to use 1.5.2 as some people suggested.

What debug information can I provide to help you to help me?

**Comment by blankster** [comment]
It's possible that I've got the same problem like https://github.com/FaisalUmair/udemy-downloader-gui/issues/242 but I've tried a lot more ways. As I said, I'm happy to provide debug information.

I've also tried to disable Kaspersky Internet Security as I thought maybe it's blocking Udeler - but this also didn't help.

**Comment by faycal95** [comment]
I dont talk about Business Login, it doesnt work since .... and no solution

**Comment by blankster** [comment]
I also wasn't talking about the business login. But I was talking about the anonymous login as proposed (together with the needed Chrome extension to auth).

**Comment by FaisalUmair** [comment]
I have released a new version [v1.7.0](https://github.com/FaisalUmair/udemy-downloader-gui/releases/tag/v1.7.0) which should allow you to login easily using the Udemy website itself. 

The new version will support all kind of accounts, be it business, google or facebook. Download, test and provide feedback.

**Comment by blankster** [comment]
Thanks a lot Faisal! I'll test it this evening and give you feedback if it works now (in the past I didn't have problems).

**Comment by Manvender-TC** [comment]
> On Windows 10 (latest patch-level) together with Udeler 1.6.3, I can't login. I've installed the Chrome extension (latest Chrome, Version 73.0.3683.86 (Official Build) (64-bit), deactivated Ublock Origin), but I don't see the anonymous login option (looks like Udeler doesn't recognize it, but the extension recognizes udemy.com and turns from activated to deactivated). I've also watched the Youtube video (https://youtu.be/adhMIaL6i9A ). What I didn't do is to download and build it from source.
> 
> ![image](https://user-images.githubusercontent.com/1443109/55428566-a0e8c280-5589-11e9-831a-b15af1b89ac6.png)
> 
> ![image](https://user-images.githubusercontent.com/1443109/55428336-2c158880-5589-11e9-96ee-9bea3cc54b63.png)
> 
> ![image](https://user-images.githubusercontent.com/1443109/55428392-49e2ed80-5589-11e9-90b9-9efcb81ef1e1.png)
> 
> ![image](https://user-images.githubusercontent.com/1443109/55428448-697a1600-5589-11e9-80ac-973500111015.png)
> 
> Next to this I've also tried https://www.udeler.com/ and changed my password, but nothing helps.
> 
> I keep getting "Incorrect Username/Password".
> 
> ![image](https://user-images.githubusercontent.com/1443109/55428628-c07feb00-5589-11e9-8eed-37f027daa36b.png)
> 
> I've no problems login into udemy.com. I thought It's maybe a language problem and even changed udemy.com from German to English - but nothing helps.
> 
> I've also tried to uninstall Udeler and reinstall it and tried to use 1.5.2 as some people suggested.
> 
> What debug information can I provide to help you to help me?



> It's possible that I've got the same problem like #242 but I've tried a lot more ways. As I said, I'm happy to provide debug information.
> 
> I've also tried to disable Kaspersky Internet Security as I thought maybe it's blocking Udeler - but this also didn't help.
Have tried this video v1.6.3. https://www.youtube.com/watch?v=adhMIaL6i9A its perfect working., please check if you still facing some issue let us know.

**Comment by blankster** [comment]
@FaisalUmair i wasn't able to test it yesterday evening but will try to do it today.

**Comment by FaisalUmair** [comment]
@blankster  No issues, do let me know when you test it. Also if you notice any improvement in download speed (if you had any issues in past with that)

**Comment by FaisalUmair** [comment]
@Manvender-TC Use v1.7.0 You don't need to use Udeler Authenticator now as v1.7.0 features popup login.

**Comment by Manvender-TC** [comment]
@FaisalUmair  Ok I had not tested that yet  but I will try and let you know.

**Comment by blankster** [comment]
@FaisalUmair it works :) (normal login, non business version).

In general, thanks a lot for your efforts and this great tool :)

To give at least something tiny back, I can also help to find out the problem with the Authenticator method which is still deactivated:

![image](https://user-images.githubusercontent.com/1443109/55575203-a4598680-570e-11e9-9f44-6880e2e0de5e.png)

Can you tell me maybe what condition you're checking to make the Authenticator method available? (on a technical level, then I can try to debug a little bit)

I don't know how the token method works, but if you tell me (or point me to the instructions), I can also test it.

**Comment by FaisalUmair** [comment]
@blankster  Business login will also work with this version, (if you have that you can test). 

And the Authenticator button will stay disabled until it establishes a socket connection with the 'Udeler Authenticator' chrome extension.

**Comment by blankster** [comment]
@FaisalUmair 

**Business Login**
Unluckily I don't have a business login, so I can't test.

**Chrome Extension/Authenticator**
As I said, I've installed the Chrome extension (version 1.0 and a screenshot that it's activated on udemy.com is attached to my initial post). It looks like there is a problem with the socket connection. For what socket connection (is there a specific port on which it is listening?) should I look?

**Access Token**
I've used [EditThisCookie](https://chrome.google.com/webstore/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg/related?hl=en) on udemy.com (while beeing logged in) and searched for access_token. It looks like a 40 char "hash". I've copy/pasted but that doesn't work. It's not necessary for me, but if you let me know how I can further "debug"/help I'm willing to help.

**Comment by FaisalUmair** [comment]
I am running a socket server on port `50490` check if your firewall is blocking that. When installing the app and running for the first time you might be seeing a prompt asking for if you want to allow this app access to that port.

And for the access token, I checked and looks like the changes I made just before releasing v1.7.0 broke this functionality, I will be fixing it in next release.
