### ISSUE TITLE
Browser login window is blank

### ISSUE THREAD

**Issue by raghavgrover** [FaisalUmair/udemy-downloader-gui#247]
Hello, After the Udeler (1.7.0) crahsed, I relaunched the software and now the second window that opens up to allow login is shown blank. Is there a way I can delete some cache? Reinstalling didn't work.

![image](https://user-images.githubusercontent.com/10961623/55686688-e2aaac00-5981-11e9-8131-327c9d14c50f.png)

**Comment by FaisalUmair** [comment]
Any steps for me to reproduce.? 
Looks like an issue with the saved settings, which don't get reset on reinstall.

Can you try checking Udemy Business and enter `www` in that field  before you click on login.

**Comment by raghavgrover** [comment]
Thank you! The issue somehow resolved on its own after 2 days.
