### ISSUE TITLE
Slow as all hell

### ISSUE THREAD

**Issue by Puyodead1** [FaisalUmair/udemy-downloader-gui#259]
![image](https://user-images.githubusercontent.com/14828766/56855768-fc089d80-691a-11e9-92c7-08c7af91eae9.png)
Any temp solutions?

**Comment by Puyodead1** [comment]
Currently using the code built from master and am getting pretty descent speeds
![image](https://user-images.githubusercontent.com/14828766/56856068-05950400-6921-11e9-81b7-d1472e7509f4.png)

**Comment by olaoluwakitan** [comment]
Hi, how did you do that? I mean the download speed. Mine is too slow, please help me

**Comment by Puyodead1** [comment]
> Hi, how did you do that? I mean the download speed. Mine is too slow, please help me

I started using a different program for now, its a python program that works on the command line.
Its called ``udemy-dl``
