### ISSUE TITLE
Add Russian Language (attached)

### ISSUE THREAD

**Issue by drweb86** [FaisalUmair/udemy-downloader-gui#26]
[ru.zip](https://github.com/FaisalUmair/udemy-downloader-gui/files/1598574/ru.zip)

**Comment by FaisalUmair** [comment]
Hi, Thanks for the translation!
However this isn't a proper way to contribute. Could you please follow this [link](https://github.com/FaisalUmair/udemy-downloader-gui/blob/master/CONTRIBUTING.md#addingupdating-a-language)

**Comment by drweb86** [comment]
Hello

I updated zip.
[ru.zip](https://github.com/FaisalUmair/udemy-downloader-gui/files/1601660/ru.zip)

**Comment by FaisalUmair** [comment]
Well thats not what I meant, Anyway, I will add the translation to the repository and will be available in next release.

Thanks!
