### ISSUE TITLE
Code looks so messy.

### ISSUE THREAD

**Issue by Doc-Han** [FaisalUmair/udemy-downloader-gui#268]
I thought of contributing to this project but It all looks so messy to me.

**Comment by FaisalUmair** [comment]
I agree, it is. I started this project just to learn Electron and nodeJS. So didn't focus on making the code modular and clean. But I now have a fair knowledge of Electron and nodeJS and had planned to rewrite this application. [https://github.com/FaisalUmair/udemy-downloader-gui/tree/2.0](https://github.com/FaisalUmair/udemy-downloader-gui/tree/2.0)

Unfortunately, I am not getting enough time to work on the planned project.

**Comment by Doc-Han** [comment]
Okay
