### ISSUE TITLE
This program is uploading Course to his Server

### ISSUE THREAD

**Issue by MacanGunung** [FaisalUmair/udemy-downloader-gui#272]
I just found out that this program is reuploading course to somewhere (drive cloud) that I believe that is Program Owner

I mad because U did it without our permission, and 
your behavior is disrespectfull

**Comment by FaisalUmair** [comment]
Hi @MacanGunung     

Do you know that this program is completely open source and the entire source code is here on this repo. Moreover the program is built using electron and you can easily view the source code of the installed program that I distribute here in the releases page. There are no native modules used or nothing such where you cannot view the exact source code.

So I suggest you one thing, do research before you come to any conclusion. You mentioned that my behaviour is disrespectful, but what's actually disrespectful is you coming here and simply mentioning that you found out that this program is stealing content. Well if you found out something, how about you show it here, discuss with me and not simply get to a conclusion by yourself.

**Comment by mabilalmirza** [comment]
@MacanGunung, how did you find out? Did you review the code?

**Comment by MikulShah** [comment]
@MacanGunung Do Not Accuse without any proof... Before giving such comment share your review points.

**Comment by clarkx86** [comment]
Proof?!

**Comment by robots4life** [comment]
Calling this nonsense. No proof given. Close the issue.
