### ISSUE TITLE
Can not log in

### ISSUE THREAD

**Issue by eacevedof** [FaisalUmair/udemy-downloader-gui#283]
As you can see I can log via web but not using Udemy-downloader.  A week ago I could login and I have not changed my user and password.

![image](https://user-images.githubusercontent.com/2829142/61536089-1c388c00-aa34-11e9-9793-b01ce6c5fef3.png)

**Comment by robots4life** [comment]
> As you can see I can log via web but not using Udemy-downloader. A week ago I could login and I have not changed my user and password.
> 
> ![image](https://user-images.githubusercontent.com/2829142/61536089-1c388c00-aa34-11e9-9793-b01ce6c5fef3.png)

Have you tried the latest release?
https://github.com/FaisalUmair/udemy-downloader-gui/releases/

**Comment by eacevedof** [comment]
> > As you can see I can log via web but not using Udemy-downloader. A week ago I could login and I have not changed my user and password.
> > ![image](https://user-images.githubusercontent.com/2829142/61536089-1c388c00-aa34-11e9-9793-b01ce6c5fef3.png)
> 
> Have you tried the latest release?
> https://github.com/FaisalUmair/udemy-downloader-gui/releases/

![image](https://user-images.githubusercontent.com/2829142/61574447-33bd5680-aac0-11e9-9d46-a22e4c499801.png)

With latest version works! thank you.
