### ISSUE TITLE
should save username (email)

### ISSUE THREAD

**Issue by muescha** [FaisalUmair/udemy-downloader-gui#29]
since i often need to restart Udeler i see this:

please save email between starts

**Comment by FaisalUmair** [comment]
Yeah, Actually I was thinking about implementing a proper logout option. However saving the username locally and keeping the user logged in can go side by side.

**Comment by tofanelli** [comment]
or just create a Json file with name and username, and make it load from there.... problem solved....  some settings like preferred languages, resolution, username and email could be saved there...

**Comment by FaisalUmair** [comment]
The app now maintains a session until the users logs out. So the user doesn't need to login every time.
