### ISSUE TITLE
Download getting stuck upon 15-20 % completion.

### ISSUE THREAD

**Issue by abhishekdeshkar** [FaisalUmair/udemy-downloader-gui#298]
Hello,

I'm facing a weird issue. While downloading a course from Udemy, it is getting stuck on 15% and then it is not able to download videos. It doesn't even download other courses. Udemy might have banned my IP or something ?

I tried to log out, delete course folder, and re login to download again but it fails over and over. What could be the issue ?

Thanks!

**Comment by sabsab22** [comment]
me too.

Login is no problem.
The download never works

**Comment by sabsab22** [comment]
ok 

now 

no problem

**Comment by Jassi10** [comment]
I am facing the same issue, it seems Udemy has blocked Udeler itself, as my downloads are getting stuck since yesterday , after some 5% to 10%, it was displaying access denied error message many times, it does not download at all and now I am trying on another computer and same issue for my login.

**Comment by abhishekdeshkar** [comment]
> 
> 
> I am facing the same issue, it seems Udemy has blocked Udeler itself, as my downloads are getting stuck since yesterday , after some 5% to 10%, it was displaying access denied error message many times, it does not download at all and now I am trying on another computer and same issue for my login.

What is your download speed ?

**Comment by snabeels** [comment]
I am getting the same error at 24%... exactly the same place 95 out of 399 items downloaded. .."Download Failed.. Click to retry". Has Udeler been blocked by udemy ? please confirm

**Comment by Jassi10** [comment]
My Download speed is 5mbps but it varies a bit ,I guess it's pretty good,.

@snabeels @abhishekdeshkar I had read @FaisalUmair had suggested in case the download fails, just delete the last .mtd file and retry, check if this works......

**Comment by snabeels** [comment]
@Jassi10 : thanks a lot for your tip.... it worked for now and download moved passed 24%
Really appreciate it (Y)

**Comment by abhishekdeshkar** [comment]
@Jassi10 @sabsab22 I had to change my static IP in order it to work. I guess Udemy blocked my IP address. I have 500 Mbps plan so.

**Comment by Jassi10** [comment]
Welcome @snabeels :)
500 mbps is awesome...... @abhishekdeshkar :) ,hope its working now.
