### ISSUE TITLE
Download location 

### ISSUE THREAD

**Issue by shohan4556** [FaisalUmair/udemy-downloader-gui#3]
Which location the videos are downloading ? Can I set location ?

**Comment by FaisalUmair** [comment]
The option to set download location is currently not available. By default the lectures will be downloaded in `Downloads` folder. The `Downloads` folder usually lies inside the `Home Directory` of the user. 

I am adding the option to select download path soon along with some other features. Check #2

**Comment by FaisalUmair** [comment]
#### Added to source code, will be available in next release. 

![Download Location Screenshot](https://user-images.githubusercontent.com/18553256/33669494-a3f588b0-dac8-11e7-826c-5fae97ae4e3c.png)

**Comment by FaisalUmair** [comment]
This feature is now available in the [latest](https://github.com/FaisalUmair/udemy-downloader-gui/releases/latest) release.

**Comment by shohan4556** [comment]
thanks
