### ISSUE TITLE
deb version request

### ISSUE THREAD

**Issue by adamkenway007** [FaisalUmair/udemy-downloader-gui#316]
hello developer could you compile and build version udeler from appimage to .deb version(or atleast make both version),make easier and give more flexibility and also it can put shortcut easily on linux user specially for newbie user

**Comment by FaisalUmair** [comment]
Sure, I will try to include more builds from next version. For now you can try to compile it yourself as per your need.  You can read the 'contributing docs' if you need help.

**Comment by adamkenway007** [comment]
> Sure, I will try to include more builds from next version. For now you can try to compile it yourself as per your need. You can read the 'contributing docs' if you need help.

Thanks ^_^
