### ISSUE TITLE
Full course list is not loading

### ISSUE THREAD

**Issue by s7oneghos7** [FaisalUmair/udemy-downloader-gui#32]
I am getting only 100 courses of 316 loading in the UI.  It seems that the 100 are the most recent courses.  I am looking for where the limit is being placed either on the server or in the code.  If it is in the code, then we need to page the course list extraction.

**Comment by FaisalUmair** [comment]
Already fixed. Download the [latest](https://github.com/FaisalUmair/udemy-downloader-gui/releases/latest) version.
