### ISSUE TITLE
The Current Search And Load More Is Not Helping Accounts With Large Number Of Courses

### ISSUE THREAD

**Issue by Alltimeovercomer** [FaisalUmair/udemy-downloader-gui#34]
Please add functionality of searching and downloading a specific course, either by name or course URL. The current search and load more does not help in this regard. 
This is very important for usability in account with more than 300 courses. Thank you, and well done.

**Comment by FaisalUmair** [comment]
Hi, I think you are right, the search filter only filters the courses that are loaded. You will have to load all the courses by clicking load more again and again and then filter the courses to find the course you were looking for. 

I will work on improving the course filter so that it works both as a course filter and a real course search which searches all your subscribed courses.

Thank you.

**Comment by FaisalUmair** [comment]
Hello @anonymiz 

Currently it only works as a desktop app because of nodejs dependency. However, I do have plans to make a web only version of Udeler.

**Comment by vikasnewports** [comment]
search is not working anymore i have numbers of courses joined , i tried short and long keywords even that full course name , half course name but getting irrelevant courses (from my courses).
Hope that u will fix it in next version or in web version

**Comment by FaisalUmair** [comment]
Hello @vikasnewports The search in the application is actually a filter which filters the courses loaded based on your input. Only the courses that are loaded will be filtered. Please check if you see a load more button at the end and try to load all courses and filter again.

I will soon implement a proper search feature which will search all subscribed courses of a user.

Thanks.

**Comment by vikasnewports** [comment]
I tried various combination but you can see the result here http://prntscr.com/in8i9l

**Comment by FaisalUmair** [comment]
Is the course you are looking for already loaded in the application? As I said before the search is only a filter and not actually search which searches your Udemy account. It only filters the results that are already loaded.

**Comment by vikasnewports** [comment]
I got it now , its hard to load all courses because I have around 12.7K courses joined .I would wait for stable solution . I have 2 requests with you for it 
1:) Download the course through URL
2:) Export the list of Joined courses (if possible )

**Comment by FaisalUmair** [comment]
Search has been fixed in v.1.5.0. You can also type course url in the search and it will search the course.
