### ISSUE TITLE
Resume does not work when we start pc

### ISSUE THREAD

**Issue by amaan22** [FaisalUmair/udemy-downloader-gui#35]
hello sir,
resume feature does not work in your software when we start our pc..
for example if course contain 200 files and i download 100 files mean completed 50% and i shut down my pc.next time when i will try to download that course it will start from 0 instead of from 50%..

it create problem with downloading big course as we can not remain online for 24 hour.
please fix this

**Comment by FaisalUmair** [comment]
Hello @amaan22 . This has been referenced before. Please check #16  

This can be fixed by adding a feature which can detect already downloaded files and resume download from the point it was stopped. I will add this feature in next release. 

Thanks.

**Comment by amaan22** [comment]
thank u.will wait for next release.

**Comment by FaisalUmair** [comment]
Please download the latest version from [here](https://github.com/FaisalUmair/udemy-downloader-gui/releases/latest)  and let me know if the problem has been resolved.

Thanks
