### ISSUE TITLE
What languages and frameworks do you use to create this awesome desktop application

### ISSUE THREAD

**Issue by jjsquackers** [FaisalUmair/udemy-downloader-gui#36]
By the way I'm a student from the Philippines and your little project really drives me into develop more.

**Comment by FaisalUmair** [comment]
Hello @jjsquackers , I am glad this project inspired you. 

Udeler is built using [electron](https://electronjs.org/). Electron is a nodejs module which allows for developing desktop apps using HTML, CSS and JAVASCRIPT.
