### ISSUE TITLE
Not able to download course from udemy

### ISSUE THREAD

**Issue by TechnoSandy** [FaisalUmair/udemy-downloader-gui#378]
Not able to download udemy course. it gets stuck in the attachment part. I am using latest version of Udeler 1.8
![image](https://user-images.githubusercontent.com/22931190/75603590-7a7f2000-5a95-11ea-9853-9915d7e4d5b8.png)
![image](https://user-images.githubusercontent.com/22931190/75603629-d77ad600-5a95-11ea-8f42-27d59bb5ebfc.png)

**Comment by FaisalUmair** [comment]
#374
