### ISSUE TITLE
Attachment downloading kept failing 

### ISSUE THREAD

**Issue by fasilmrm** [FaisalUmair/udemy-downloader-gui#383]
@FaisalUmair  i'm facing this issue of freezing while downloading the attachments.. i'm using the latest version of udler. I tried to delete the last file manually, but still facing the problem.. any method to fix it. thanks in advance
![Udler Problem](https://user-images.githubusercontent.com/61681381/75654786-7cf49c00-5c86-11ea-82ac-c6eb79037b00.png)

**Comment by sajangurung2015** [comment]
so, the workaround till this issue gets fixed is to click on SETTINGS, tick the SKIP ATTACHMENTS option and save the settings.... It will download the videos without any interruptions ... For the attachments (PDFS, images, and so on) that come with the course, you have to go one by one  through the course content and download them manually .....

**Comment by fasilmrm** [comment]
> so, the workaround till this issue gets fixed is to click on SETTINGS, tick the SKIP ATTACHMENTS option and save the settings.... It will download the videos without any interruptions ... For the attachments (PDFS, images, and so on) that come with the course, you have to go one by one through the course content and download them manually .....

Thanks for your reply

**Comment by edleyrocha** [comment]
I have the same problem, Udeler is not downloading the attachments. Udemy has changed something in its API.

**Comment by edleyrocha** [comment]
> so, the workaround till this issue gets fixed is to click on SETTINGS, tick the SKIP ATTACHMENTS option and save the settings.... It will download the videos without any interruptions ... For the attachments (PDFS, images, and so on) that come with the course, you have to go one by one through the course content and download them manually .....

I want to download with all attachments. Some way without being manually?

**Comment by fasilmrm** [comment]
> > so, the workaround till this issue gets fixed is to click on SETTINGS, tick the SKIP ATTACHMENTS option and save the settings.... It will download the videos without any interruptions ... For the attachments (PDFS, images, and so on) that come with the course, you have to go one by one through the course content and download them manually .....
> 
> I want to download with all attachments. Some way without being manually?

I have no idea.. @FaisalUmair

**Comment by FaisalUmair** [comment]
#374

**Comment by fasilmrm** [comment]
> #374

Thanks for the help, I appreciate your sincerity
