### ISSUE TITLE
Another White screen problem

### ISSUE THREAD

**Issue by abban270** [FaisalUmair/udemy-downloader-gui#392]
Hi admin
First thanks for the perfect tool and the updates.
My OS : (Win7 : 32Bit)
there is no probleme with versions ( 1.7.0 and lower..)
![Sans titre](https://user-images.githubusercontent.com/50278545/76010029-8003bc80-5f12-11ea-847e-dce3c3d2125c.png)

But i have a problem when i open the application with 2 versions (v1.8.0 , v1.8.1)
![Sans titre2](https://user-images.githubusercontent.com/50278545/76010033-83974380-5f12-11ea-8ebd-8abd9b147859.png)
is there any solution for that
thanks in advance

**Comment by FaisalUmair** [comment]
Are you seeing this white screen immediately after you open the application? or does it show up when you try to download a course?

**Comment by abban270** [comment]
i see white screen immediately after application was oppened

**Comment by BobRoyAce** [comment]
I keep seeing the white screen, after Udeler downloads three or four video files. At that point, the application can't be closed either...have to use Task Manager to close it. I am using 1.8.0 on Windows 10 machine. I would love it if this could be resolved as I have very much enjoyed using the app to download courses that I have purchased, both quickly and easily! I should probably note that, for some reason, I was able to download one course, but the four others that I have tried to download are having this issue. However, I should also note that one of the courses downloaded more videos, before the problem occurred...like twenty or thirty something videos.

![image](https://user-images.githubusercontent.com/57853357/76489905-1434be80-6400-11ea-8785-5759d65e5920.png)

**Comment by BobRoyAce** [comment]
I just installed version 1.8.2 and the problem isn't happening...don't know if that solved it or if something else was wrong that resolved itself.

**Comment by abban270** [comment]
Problem **Sloved**:
i have update **Java Runtime**
thanks for you buddys

**Comment by Abhi904485** [comment]
Hi @abban270  in my case java version is below one , do i need to update the same i am using mac osx catalina .

java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)

**Comment by abban270** [comment]
@Abhi904485 
if you have the same problem
you must update your Java Runtime version
because there are some updates on the last one

**Comment by abban270** [comment]
Sloved Problem thanks
