### ISSUE TITLE
I have about 48 courses, but i am getting listed only 12 course.

### ISSUE THREAD

**Issue by dgharami** [FaisalUmair/udemy-downloader-gui#4]

**Comment by FaisalUmair** [comment]
Fixed in https://github.com/FaisalUmair/udemy-downloader-gui/commit/b92086ce54a70ca45e9fbdeb29eca62ad7e0ebb0 will be available in next release. However you can follow the Developer instruction in the readme file to use this feature now.

Thanks for reporting 👍

**Comment by FaisalUmair** [comment]
The changes made are now available in the [latest](https://github.com/FaisalUmair/udemy-downloader-gui/releases/latest) release.

Download the new version and it should show all the courses you have enrolled in.
