### ISSUE TITLE
Another White Screen on giving Udemy Business Account 

### ISSUE THREAD

**Issue by Abhi904485** [FaisalUmair/udemy-downloader-gui#400]
Udeler Version :  1.8.2
 java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)
![image](https://user-images.githubusercontent.com/31724671/76742123-a2a99700-6796-11ea-9e3e-2102d0f2fe9c.png)

**Comment by abban270** [comment]
please try to update your version to:
**Version 8 Update 241** 
and tell us the result

**Comment by Abhi904485** [comment]
hi @abban270  i did update , White screen problem is still there 

<img width="1383" alt="bug" src="https://user-images.githubusercontent.com/31724671/77031817-ba686180-69c8-11ea-82d9-8127513063c3.png">

**Comment by abban270** [comment]
can you try this version: 1.6

**Comment by Abhi904485** [comment]
problem is not with version , whatever udemy business name i am giving in that name was wrong 

For Example i am working in company name **abc**  and my mail is **abhishek@abc.com**  .. So in udeler after selecting checkbox  udemy business you only need to give **abc**  then click on login after that it will ask for  your company email and password . 


So what i doing wrong after selecting i am giving **abhishek@abc.com** but it was supposed to  **abc**


So that is not bug , it is my mistake .
