### ISSUE TITLE
I am not able to login 

### ISSUE THREAD

**Issue by pradeepnegi88** [FaisalUmair/udemy-downloader-gui#404]
<img width="542" alt="Screenshot 2020-03-21 at 08 51 48" src="https://user-images.githubusercontent.com/17610510/77218430-3beafb80-6b51-11ea-9105-dddfbdb40238.png">

**Comment by pradeepnegi88** [comment]
Version 1.8.2

**Comment by abban270** [comment]
@pradeepnegi88  there is a trick
try to download this version: 1.6
login with your email and password
than download the new version and problem wil be sloved
