### ISSUE TITLE
Password compromised few days after using this software

### ISSUE THREAD

**Issue by llpj** [FaisalUmair/udemy-downloader-gui#41]
Did anyone have similar experience ?

**Comment by FaisalUmair** [comment]
Hello @llpj  Your credentials are sent to Udemy servers directly for authentication. This projects is open source, anyone can check the source code to determine if there is anything suspicious. 

Also the executable contains same code and can be extracted and checked. Did you download the application from here or from any other source?

**Comment by llpj** [comment]
I am not sure as it was installed in another computer which may have been compromised. 
Thank you for help. Cheers!
