### ISSUE TITLE
Internet connectivity breaks

### ISSUE THREAD

**Issue by Psp29onetwo** [FaisalUmair/udemy-downloader-gui#424]
Everytime when i download course on udeler my internet connectivity brokes next day and i have to call broadband operator to fix it every single time it happens

**Comment by edy-dev** [comment]
> Everytime when i download course on udeler my internet connectivity brokes next day and i have to call broadband operator to fix it every single time it happens

This is not a problem with the app. This is a problem with your internet provider that is limiting your internet daily.

Please close this error.

**Comment by Psp29onetwo** [comment]
Ok thank you for reply
