### ISSUE TITLE
I can only download the first lecture of the course. 

### ISSUE THREAD

**Issue by ilbrigz** [FaisalUmair/udemy-downloader-gui#45]
Only downloads the first lecture

**Comment by FaisalUmair** [comment]
Does this happen for all courses?

**Comment by vikasnewports** [comment]
working fine at my end download 4 courses but I am facing the other issue is that I can not search any course even that with full course title or half course title or part of it ..
is it possible that just provide the course link to select the download instead of search ,

**Comment by FaisalUmair** [comment]
@vikasnewports  Please check the reply on #34

**Comment by ilbrigz** [comment]
Oh,, I unchecked the download start/end and it seems to work now. Sorry for that. Thanks for this awesome app by the way!
