### ISSUE TITLE
بخصوص ملفات الترجمة

### ISSUE THREAD

**Issue by sabsab22** [FaisalUmair/udemy-downloader-gui#46]
عمل ممتاز جدا جدا . حبيت استفسر عن ملفات الترجمة متى بتكون النسخة اللي تدعم ملفات الترجمة .

**Comment by FaisalUmair** [comment]
I am not sure what google translate says is what you actually meant. 

But if you are asking about Arabic translation. It is currently not available but you can be the one who makes it available to yourself and everyone else. Please check https://github.com/FaisalUmair/udemy-downloader-gui/blob/master/CONTRIBUTING.md

I don't even know if you can read English. But I hope you get the message somehow.

**Comment by sabsab22** [comment]
I mean
download subtitle for courses 
https://github.com/FaisalUmair/udemy-downloader-gui/issues/23

ok 

^_^

**Comment by FaisalUmair** [comment]
Will add that feature soon.

**Comment by thetopengineer** [comment]
please i want to download subtitle for courses
and if you can develop your program to **choose download subtitles or videos only** because i download subtitles manual this take along time And Thank you sir i hope to do that soon

**Comment by FaisalUmair** [comment]
@thetopengineer I have already implemented this feature in my local version of the repository. It will be included in the next release.

**Comment by FaisalUmair** [comment]
Support for downloading subtitles has been added in v1.5.0
