### ISSUE TITLE
Changelog for 1.4.0

### ISSUE THREAD

**Issue by tofanelli** [FaisalUmair/udemy-downloader-gui#48]
hey @FaisalUmair 

what is the changelog for this new version??

cheers =)

**Comment by FaisalUmair** [comment]
Please read the release [description](https://github.com/FaisalUmair/udemy-downloader-gui/releases/tag/v1.4.0)

Thanks

**Comment by tofanelli** [comment]
Superb! I haven't seen it.... sorry =)

**Comment by FaisalUmair** [comment]
No issues :)

**Comment by FaisalUmair** [comment]
I forgot to update the changelog (Updating it now). Actually it was a critical update to adapt new Udemy api structure as the app was broken.

**Comment by tofanelli** [comment]
ah.. ok... superb then

And what about the lecture names, instead resetting on each module, leave as is? any idea when?

**Comment by FaisalUmair** [comment]
Yes. After next release.

For next release I am working on three main features. 
1. Better search function.
2. Lecture Subtitles
3. Separate download tab.
And also some bug fixes like resume download on expired download links.

I have already finished **1** & **2** and about to complete **3**. I hope the new release makes the app much stable and improves the course download workflow.

**Comment by tofanelli** [comment]
Amazing features to be added... .

mind if I ask for one?

Let me past the course link and download it, so it will be way easier than fetch all courses to download only one... what you think? =)

**Comment by FaisalUmair** [comment]
That would be really nice addition. I think someone else had also requested for the same. I think we should integrate it with the search function. So if the user enters course link it will simply download it instead of searching.

And I have finished working on separate downloads tab and I will most probably publish a new release tomorrow. I will see if I can include the course link download feature in the next release. If not then definitely in the immediate release after next.

**Comment by tofanelli** [comment]
This is amazing!!!

For me, there is only 3 things missing on your app

1- find a course trough a link and download from it
2- not reset lectures numbers on each module
3- move quizzes to a "quizzes"" folders and zip files to a "attached_folder", just like udemy-dl does.... some courses has dozens of zip files, and makes the videos folder so poluted =\

For me, there is any other addition to do =)

**Comment by tofanelli** [comment]
hey @FaisalUmair ... there is no changelog for versions above 1.4.0....  what was fixed / added?
