### ISSUE TITLE
Downloading speed is slow

### ISSUE THREAD

**Issue by saifullah9002** [FaisalUmair/udemy-downloader-gui#49]
> download speeds are very low even on high speed internet.
Please add a downloading tab so that we can see what is downloading.
Or add directly download to google drive.

**Comment by FaisalUmair** [comment]
Hello @saifullah9002 

In the latest version ( v.1.4.0 as of now), the number of downloading threads is limited to 1 for stable downloads. In next version I will add the option to change the number of downloading threads or if found to be causing no harm, then increase it to max by default.
Please download any old version to see what speed you get at max threads.

And for the downloading tab, I think the main screen is itself a downloading tab. As it shows you what is downloading.

The idea to add download to google drive is great. I will try to implement that. 

Thanks.

**Comment by saifullah9002** [comment]
Thanks alot

**Comment by FaisalUmair** [comment]
Fixed in v.1.5.0.
