### ISSUE TITLE
add user information panel

### ISSUE THREAD

**Issue by mertayya** [FaisalUmair/udemy-downloader-gui#526]

**Comment by vega7473** [comment]
Why don't you log out and then when loggin back in again the email should show

**Comment by mertayya** [comment]
> Neden oturumu kapatmıyorsun ve tekrar giriş yaptığında e-posta nın göstermesi gerekiyor
It was not showing in the sessions I had in the past and I am afraid of losing my course if I log out.

**Comment by vega7473** [comment]
There is no other to see the registered email address

Did you have any problems with downloads getting stuck or  the software unable to build course data? (i do)
