### ISSUE TITLE
I can't log in To My Business account !

### ISSUE THREAD

**Issue by viniciosds** [FaisalUmair/udemy-downloader-gui#537]
I just downloaded version 1.8.2 but I can not log in, opens a second screen(Pop up) blank .

Could anyone help me ?

![Udeler](https://user-images.githubusercontent.com/13534245/102404264-33333300-3fc6-11eb-8149-af33ff7540ac.png)

**Comment by devameer** [comment]
write your business name  just
like this:
btitlearning

**Comment by devameer** [comment]
@viniciosds 

write your business name  just
like this:
btitlearning

**Comment by viniciosds** [comment]
> @viniciosds
> 
> escreva o nome da sua empresa
> assim:
> btitlearning

@devameer 

Thank you very much, it worked !

**Comment by rahuljames01** [comment]
ya it really work. you have to just type following syntax
companyname-> login using access token
now i am able to access my account but not able to download course, it just reloading .
@viniciosds @devameer please suggest
