### ISSUE TITLE
Loading Courses spinning indefinitely  

### ISSUE THREAD

**Issue by rajeevshukla** [FaisalUmair/udemy-downloader-gui#54]
I am able to log in using udemy business account. I also added https://<subdomain>.udemy.com but I see loading courses spinner is spinning indefinitely. How to fix that?

**Comment by FaisalUmair** [comment]
Business name is just the name of the business, not the full url. For example if the business url is http://apple.udemy.com/ then the business name should be "apple"

**Comment by rajeevshukla** [comment]
Thanks. It worked.
