### ISSUE TITLE
Unable to resume download

### ISSUE THREAD

**Issue by Blair2004** [FaisalUmair/udemy-downloader-gui#57]
Hi, 
thank you for your tools.
I've been using it to download a courses (premium) on Udemy, but i wasn't able to complete the download on the same day, so i came back later to resume it, but after loading, the download stick at the same place for hours and the download rate speed doesn't change.

![image](https://user-images.githubusercontent.com/5265663/38214217-daf82bf2-36bb-11e8-8a3b-1b0967abf0ea.png)

Thank you.

**Comment by FaisalUmair** [comment]
This is a known issue where the download stops on expired download links, but in most cases it moves on to next file after timeout. But in your case it is a attachment so I guess it wont automatically skip and move to next file.

Here is what you can do. 
Close the application, go to the folder where the course is being downloaded. Navigate to the last folder and delete the last file, come back to the software and try resuming download. If it doesn't resume try deleting more files (incomplete files which have .mtd extension).

Let me know if it helps.

**Comment by Blair2004** [comment]
That helped thank you.
