### ISSUE TITLE
![image](https://user-images.githubusercontent.com/12404006/115875602-969b0900-a46f-11eb-90ee-3e39c25c7170.png)

### ISSUE THREAD

**Issue by pypycode** [FaisalUmair/udemy-downloader-gui#578]
![image](https://user-images.githubusercontent.com/12404006/115875602-969b0900-a46f-11eb-90ee-3e39c25c7170.png)
Please help me, why does not appear language subtitles, I wait for one hour but still does not see
let me know why ? :(

_Originally posted by @pypycode in https://github.com/FaisalUmair/udemy-downloader-gui/issues/172#issuecomment-825647633_

**Comment by goldoft** [comment]
Hello
I have the same problem, we cannot download the courses. We hope a solution to this problem
