### ISSUE TITLE
Not able to run on heroku

### ISSUE THREAD

**Issue by nk932714** [FaisalUmair/udemy-downloader-gui#58]
Giving application error while running on heroku

**Comment by FaisalUmair** [comment]
I am not sure what you are trying to do. This is an electron app and needs to launch a chromium browser to render frontend. Are you trying to launch this headless?

**Comment by nk932714** [comment]
Thanks for your quick reply @FaisalUmair  sorry for raising issue without complete reading full description.

I was thinking this is an app which will run on node.js and after deploying on Heroku( or any other platform which supports node.js)  it will open a webpage to login with udemy and download the videos through webpage.

But i think it is not ment for that purpose.
