### ISSUE TITLE
Unable to download TOP COURSES.

### ISSUE THREAD

**Issue by ghost** [FaisalUmair/udemy-downloader-gui#582]
@fatihyIdz1 who commented below is  POOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOP

**Comment by fatihyldz1** [comment]
don't spam, read existing issues before creating a new one.

**Comment by ghost** [comment]
SHUT THE FUCK UP YOU MOTHER FUCKING BASTARD.

YOU ARE A ....DOG POOP AND CHICKEN POOP AND COCK POOP AND SWINE POOP

YOU MOTHER POOPED YOU OUT OF VAGINA WHERE YOUR FATHER POOPED HIS SPERMS INTO YOUR MOTHER'S VAGINA POOP HOLE !!!!
