### ISSUE TITLE
Not loading courses

### ISSUE THREAD

**Issue by PradeepKusuma** [FaisalUmair/udemy-downloader-gui#63]
I am trying to login with udemy business credentials, but I am unable to load the videos. The screen continuously showing loading black screen.

**Comment by FaisalUmair** [comment]
What do you type in `Udemy Business Name` field?

**Comment by p4princea** [comment]
Hi Faisal, I'm also facing the same issue. Can you please tell what should be the syntax for `Udemy Business Name` ?
I have tried passing `https://<company profile>.udemy.com/` and `<company profile>.udemy.com`
The login is successful in both the cases but it stucks at *Loading Courses*.

![image](https://user-images.githubusercontent.com/38970068/39613090-7b17661e-4f82-11e8-95ff-ebee6d424fec.png)

**Comment by p4princea** [comment]
@FaisalUmair It worked. Thanks. I think this issue can be closed now.

**Comment by PradeepKusuma** [comment]
Thank you so much FaisalUmair, it has worked fine for me.

**Comment by gitanbu** [comment]
same issue , i am facing , but course name not listed

**Comment by akhilpadgilwar** [comment]
> Hi @p4princea You only need to write `company profile` in the `Udemy Business Name` field.
> 
> Check the screenshot for example on https://apple.udemy.com/
> ![screen shot 2018-05-04 at 11 52 46 am](https://user-images.githubusercontent.com/18553256/39615085-cdbe08fa-4f91-11e8-9786-81bad147599c.png)

can you help me with this error.

![image](https://user-images.githubusercontent.com/45946251/50855781-d600c280-1356-11e9-8abc-5f8ffd391c5b.png)
