### ISSUE TITLE
Course is already downloaded notification

### ISSUE THREAD

**Issue by itsmemac** [FaisalUmair/udemy-downloader-gui#64]
Need a notification or an indication that "The tutorials is already downloaded"
Maybe give a option like "Re-Download" in the indication so that we can redownload the tutorial is its already download. It can be useful who has more number of tutorials.

**Comment by FaisalUmair** [comment]
Hi, Yes I agree with you.  This options is required and I will surely work on this. 

Thanks.

**Comment by FaisalUmair** [comment]
This issue has been taken care of, if you download a course which has been already downloaded. It will  just show Download completed and won't download the course again. In case you want to download the course again you can delete/move the downloaded course and try downloading again.
