### ISSUE TITLE
Bad permissions on some files

### ISSUE THREAD

**Issue by Smitty010** [FaisalUmair/udemy-downloader-gui#66]
Not sure what this one is about.  I download a class.  It downloads fine (no errors).  Then I copy the directory with the class files in it to a different drive.  On a small percentage of the files I get an error message saying that administrator rights are needed to do the copy.  I click continue (since I'm the administrator of my machine) and then I get an unable to copy message.  Looking at the directory I'm copying to, it looks like the file actually gets copied, but I'm unable to delete the original file.

It's very random and doesn't happen on all classes (that is some classes copy with no errors).  It feels like you are not setting the permissions on a file and they are getting whatever random value is in the permissions fields when the file is created.  Again, it only happens on a small percentage of the files (maybe 1 out of 100 or less).

Probably should add that I'm running Windows 10.

**Comment by FaisalUmair** [comment]
While I was fixing an issue related to expired download links, I found that the downloader I am using is not properly closing the files which are opened while trying to resume download. 

I fixed the issue and I think this should also fix the bad permission problem as the files would no longer be held by another program/user/group.
