### ISSUE TITLE
Not Downloading

### ISSUE THREAD

**Issue by ertandag** [FaisalUmair/udemy-downloader-gui#68]
It says Building Course Data. Not download.

**Comment by Gauthamkan** [comment]
Hi Faisal,

I am using the latest 1.4 version and since morning it shows Building course Data and there is no progress after that.

Could you please help us resolve this issue. ASAP.

Thanks in Advance.

**Comment by saprogramming34** [comment]
I have the same problem @FaisalUmair

**Comment by lukino999** [comment]
I downloaded this app yesterday and it was working fine. 
I did try it today it is stuck on Building Course Data.
Thanks

**Comment by trank2012** [comment]
Confirm. Not downloading

**Comment by kathstenby** [comment]
I am experiencing the same issue.  Something changed on the Udemy side yesterday(04/25) morning.  While performing a download on a class the download stopped and was stuck at 23%.  Now when I click a class to download its stuck on Building Course Data.   I hope this information helps.  Thanks

**Comment by FaisalUmair** [comment]
Thank you all for reporting this.

I will look into this and push an update as soon as possible.

**Comment by George-01** [comment]
Hi Faisal,
I have tried downloading my courses several times today, i keep getting 'Building course data'. Nothing else. Kindly help to resolve this. Regards.

**Comment by FaisalUmair** [comment]
@George-01 , Please read my comment above (I have updated it)

**Comment by alxRlja** [comment]
Thank you for your efforts @FaisalUmair . I hope it will be ready soon. I have to travel  and I'll love to be able to study on the plane.   :-)

**Comment by George-01** [comment]
Hello again Faisal,good work. I have the latest update installed, i keep getting 'Building course data'. Nothing else. Kindly help to resolve this. Regards.

**Comment by FaisalUmair** [comment]
@alxRlja I have published the new version. Download the latest version from [here](https://github.com/FaisalUmair/udemy-downloader-gui/releases/latest)

**Comment by George-01** [comment]
Good work Faisal, work well again. Many thanks.

**Comment by ElinaldoAmancio** [comment]
Bom dia Faisal!
Voltou a funcionar.
Obrigado por compartilhar.
Um forte abraço, saúde e Paz!

**Comment by fernandosabrazil** [comment]
you are downloading only the introduction.

**Comment by FaisalUmair** [comment]
@fernandosabrazil  Please check if you have enabled Download Start/End in the settings, that could be the reason for the program to download only few lectures.

**Comment by centuryx476** [comment]
Hello,
I downloaded the updated version and the courses are now downloading perfectly.
Thank you very much...
If I may ask what was the issue you had to resolve ?
Did the website change their API ? 
or something else 

I am interested to know 

Thanks

**Comment by FaisalUmair** [comment]
@centuryx476 There was a slight change in the response from API. Udemy used to return html source for the video player and within that source we could find video links. But now they have a separate key for the links and therefore I had to follow the new api structure to fix the issue.

Check https://github.com/FaisalUmair/udemy-downloader-gui/commit/5a11279a60202a119becad9b8284d60f1e50b878 for viewing the changes I made.

**Comment by centuryx476** [comment]
@FaisalUmair 
I see now the very SUBTLE changes that udemy did. 
Thanks
I think you are one of the first to fix this as others have not addressed this yet. 
youtube-dl and some other downloaders are currently not working for udemy.com

but yours is. 

So thanks again

**Comment by mrozmanith** [comment]
I got the same error with 1.4.1  I switched download settings from 'auto' to 480p and that fixed it.  Will also try 720p

**Comment by mrozmanith** [comment]
Hmmm.  that worked for about 15 minutes and now not downloading again.  0 bytes/sec.  Are they throttling downloads?

**Comment by FaisalUmair** [comment]
@mrozmanith  For me it is working fine. What about now? May be it was a temporary glitch.

**Comment by JuanPabloVelezArroyave** [comment]
I have got a next problem : 
sudo: udeler*.AppImage: command not found
