### ISSUE TITLE
The program is downloading only the introduction

### ISSUE THREAD

**Issue by fernandosabrazil** [FaisalUmair/udemy-downloader-gui#71]
![1](https://user-images.githubusercontent.com/38814745/39398649-21e27ca4-4ae7-11e8-9ba1-f30329e22f7e.PNG)
![2](https://user-images.githubusercontent.com/38814745/39398650-2205cf1a-4ae7-11e8-8f10-048be3aaa417.PNG)

**Comment by FaisalUmair** [comment]
Hi, Please check if you have enabled Download Start/End in the settings, that could be the reason for the program to download only few lectures.

**Comment by fernandosabrazil** [comment]
Thank you! It's working correctly.
