### ISSUE TITLE
needs way faster download speed, way better search function, and a download all enrolled courses button/option

### ISSUE THREAD

**Issue by apalm1341** [FaisalUmair/udemy-downloader-gui#72]
This app is really cool man and I give you ton of credit. However, you definitely need to make the app be able to download the courses much much faster. Also, you really need to better the search function. A ton of my courses are not showing up when I search them. And it would be really cool if there was a download all my enrolled courses option/button. I am also having trouble downloading many courses at same time with it being very slow and it bringing up "download failed click this message to retry" on tons of courses.

**Comment by apalm1341** [comment]
can/will u get all this working soon?

**Comment by FaisalUmair** [comment]
@apalm1341 Yes I will for sure. These improvements are already on the line. The speed was intentionally brought down by limiting the download threads to 1 and the reason for that was to make downloading more stable than it was at that time. But now I guess  we have other things in place to take care of it and therefore we can try to max out the number of threads again. 

If you want to try increasing the number of threads yourself, you can clone the repo and change the number of threads in `assets/js/app.js` file.

And for the search function, I have mentioned it multiple times in other issues related to search that we only have a course filter as of now there is no proper search option. It only filters the courses (by name) that are already loaded. 

I have many plans for this project, but unfortunately I am not able to get enough time to work on this and hence implementing new feature or fixing any issues take time than usual.

**Comment by apalm1341** [comment]
when will u get all these issues working that I mentioned? And are/should all enrolled courses be in the app/program?

**Comment by FaisalUmair** [comment]
I cannot say for sure when will I update it, but I am working on the same and have already implemented the search function (which will be available in next release).

**Comment by apalm1341** [comment]
can u comment here when u make the new release ready to be used/downloaded? How will I know when it is ready?

**Comment by apalm1341** [comment]
r u gonna need more time for newest version of app/program?

**Comment by FaisalUmair** [comment]
Yes. I am currently working on separate download tab to manage active downloads. I have already finished working on the search function and subtitles. 

Once the download tab is ready, I will push a new release with these 3 features and also some bug fixes which should improve download speeds.

**Comment by FaisalUmair** [comment]
@apalm1341 I have committed all the changes planned for next release. You can try the next version now by cloning the repo and running it from its source. If you are not familiar with such stuff then wait for me to upload the compiled files. I will test the app first for different scenarios on various platforms and then publish the new release.

**Comment by apalm1341** [comment]
cloning repo and run it from its source? not sure what u mean. upload compiled files? not sure what u mean by any of this. I thought i downloaded your app/program through GitHub before and then just ran a .exe file that let me use udeler app/program but not totally sure. I cant remember what exactly i did.

**Comment by apalm1341** [comment]
ya, I'm pretty sure i clicked download zip after clicking clone or download in GitHub. then, i ran exe file which let me use udeler. I assume "upload the compiled files" means u will add .exe file so that I will be able to just run that file like i did before in order to access/use udeler app/program?

**Comment by FaisalUmair** [comment]
Never mind @apalm1341 As I mentioned that if you are not familiar with all this, you can wait for me to upload the compiled files. And yes by compiled files I mean the actually software (.exe file) that you can run.

**Comment by apalm1341** [comment]
Ok. When will u be uploading compiled files?

**Comment by FaisalUmair** [comment]
I would have already uploaded the files, but I am facing some issues on windows during testing. On mac, linux everything works as expected.

As soon as I get everything working on windows as well, I will upload the files.

**Comment by FaisalUmair** [comment]
I have published the new version. Download it from [here](https://github.com/FaisalUmair/udemy-downloader-gui/releases/latest)
