### ISSUE TITLE
The course without download link on the site cannot be downloaded in udeler 

### ISSUE THREAD

**Issue by hussylalani** [FaisalUmair/udemy-downloader-gui#79]
There is a course which do not have download link on the udemy website and i tried downloading the course through the udeler application but its stuck on "building course data". Its stuck on above message since couple of hours. Can udeler download courses which do not have download link on the websites? Your help is appreciated. Thank you.

**Comment by FaisalUmair** [comment]
Hi @hussylalani  I would need the course link to check whats wrong. 

And what version are you on?

**Comment by vesper8** [comment]
I am experiencing the same problem with this course

https://www.udemy.com/hands-on-infrastructure-automation-with-ansible

It looks like something's changed recently.. but the videos are still easy to locate using other chrome extensions so it's probably not too hard to fix

**Comment by FaisalUmair** [comment]
@vesper8 Are you facing this issue only with the course you mentioned.? 
What version are you on?

**Comment by FaisalUmair** [comment]
@hussylalani  @vesper8  Do you still face the same problem in v1.5.4? If yes, share some details like at what lecture it freezes. Its hard for me to fix without much info and without having access to the same course.

**Comment by vesper8** [comment]
I ended up installing https://github.com/r0oth3x49/udemy-dl and that one was already patched so I can't say if yours works now sorry

**Comment by FaisalUmair** [comment]
@vesper8 No issues. Actually in order for me to fix the issues related to specific courses I need to have access to the course. 

I am closing this issue for now.

**Comment by nishantcx** [comment]
https://www.udemy.com/tableau-for-marketing/ 
I am trying to download this course and it fails every time at 16%. Please help asap.
