### ISSUE TITLE
New release/version soon?

### ISSUE THREAD

**Issue by apster906** [FaisalUmair/udemy-downloader-gui#81]
When will you upload the compiled files to github so people can download the newest version of udeler app? Are you almost done? It has been a while since there has been a new version of udeler.

**Comment by apster906** [comment]
Can u upload the compiled files today since it sounds like everything else is working fine?

**Comment by FaisalUmair** [comment]
I can upload the Mac and Linux version. But for windows version, it is still not a stable solution it fails in some cases. But I am positive that I will get it working till tomorrow as I am making even progress.

So I can upload all files tomorrow hopefully.

**Comment by FaisalUmair** [comment]
Mac and Linux versison will only work on their respective operating systems and not on windows. 

I will upload windows version tomorrow if I get it working by then. 

Actually I think I should upload all versions tomorrow as  most users here are on windows and it will be confusing for them.

**Comment by FaisalUmair** [comment]
I have published the new version. Download it from [here](https://github.com/FaisalUmair/udemy-downloader-gui/releases/latest)

**Comment by apster906** [comment]
It still isnt showing certain courses im searching for

**Comment by apster906** [comment]
im using 64 bit newest version for windows

**Comment by FaisalUmair** [comment]
Closing this issue, as it is unrelated to the archived course and the original issue has been resolved.
