### ISSUE TITLE
Still search is not working well

### ISSUE THREAD

**Issue by ashik685** [FaisalUmair/udemy-downloader-gui#84]
Search is a vital option for your software sir. I think you should fix it first.

**Comment by FaisalUmair** [comment]
Fix for search has already been committed and I will release a new version very soon which will include a proper search function.

**Comment by FaisalUmair** [comment]
@ashik685  Download [latest](https://github.com/FaisalUmair/udemy-downloader-gui/releases/latest) version of the app. It includes a fix for search option.

**Comment by vikasnewports** [comment]
search is still not working fine , i think we need to load all courses ?

**Comment by FaisalUmair** [comment]
@vikasnewports What issue are you facing with course search? And no you don't need to load all courses.

**Comment by ashik685** [comment]
Now need another option , remember me option. So that we don't need to login always

**Comment by ashik685** [comment]
Search is working fine :+1:
