### ISSUE TITLE
to resolve a html problem

### ISSUE THREAD

**Issue by mohilles** [FaisalUmair/udemy-downloader-gui#85]
https://github.com/FaisalUmair/udemy-downloader-gui/blob/f87e8f94c7f40cada7d74ce236864f26e6b8b160/assets/js/app.js#L290

**should be** 
```javascript
var src = response.asset.data.body;
```

AND 

https://github.com/FaisalUmair/udemy-downloader-gui/blob/f87e8f94c7f40cada7d74ce236864f26e6b8b160/assets/js/app.js#L286

**should be** 
```javascript
url: `https://${subDomain}.udemy.com/api-2.0/users/me/subscribed-courses/${courseid}/lectures/${v.id}?fields[asset]=stream_urls,download_urls,captions,title,filename,data&fields[lecture]=asset,supplementary_assets,`
```

**Comment by FaisalUmair** [comment]
You are looking at a old version of Udeler source code. The current version is v1.4.1
