### ISSUE TITLE
Is udeler app legal?

### ISSUE THREAD

**Issue by apster906** [FaisalUmair/udemy-downloader-gui#86]
Is it legal for all people to use this udeler app?

**Comment by sajjadjutt4u** [comment]
Being a software engineer.  i would like to say that they might save our user_id and password. they can also extract our credit card information. 

so.....

**Comment by AronWater** [comment]
> Being a software engineer. i would like to say that they might save our user_id and password. they can also extract our credit card information.
> 
> so.....

you could definitely look at the source code and compile yourself.   

But I do want to know that it is 100% legal to write program to crawl something even if you could manually download it.   One counter example is that it is likely to be illegal to  crawl something on bank account website, despite the fact that you could manually visit the site.

**Comment by sajjadjutt4u** [comment]
No doubt ! They can save our personal information like id or password. 

There are other applications which can see our data. Like google, Facebook. Etc 

There is only a relationship of trust between developer or user. For now, I didn’t heard any complain of data stealing. So we can rely on it.

**Comment by AronWater** [comment]
> No doubt ! They can save our personal information like id or password. There are other applications which can see our data. Like google, Facebook. Etc There is only a relationship of trust between developer or user. For now, I didn’t heard any complain of data stealing. So we can rely on it.
> […](#)
> Sent from my iPhone
> On 03-Sep-2019, at 8:31 PM, Aron Water ***@***.***> wrote: Being a software engineer. i would like to say that they might save our user_id and password. they can also extract our credit card information. so..... you could definitely look at the source code and compile yourself. But I do want to know that it is 100% legal to write program to crawl something even if you could manually download it. One counter example is that it is likely to be illegal to crawl something on bank account website, despite the fact that you could manually visit the site. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

What I mean is that you could surely view the source code yourself,  in that way you could know whether the author capture our data or not,      and I am pretty sure he is not because I have viewed the code,  and after that, you could compile the code into the binary executable for your operating system, for me , it is Mac Os.  So basically , if you are careful enough and understand the source code, no need to worry about the security.


The main concern is that whether this program is 100% legal for daily use.

**Comment by sajjadjutt4u** [comment]
could you please send me the code?

**Comment by surajkale24** [comment]
Okay ,they might save our user_id and password. they can also extract our credit card information. if doing any transaction with help of our credit card information then everyone getting OTP & bank messages alerts then you can immediately take actions on it right. so its not so easy .only on trust & security also.
