### ISSUE TITLE
new features?

### ISSUE THREAD

**Issue by apster906** [FaisalUmair/udemy-downloader-gui#89]
I thought newest version of udeler was gonna have more features such as archived courses section and button to download all enrolled courses and button to download all archived courses? R u gonna add all these features (would be awesome) and when?

**Comment by FaisalUmair** [comment]
Well I had already mentioned that for new version I am working on:
Separate downloads tab
Support for Subtitles
Better Search function

Support for archived courses and download all courses button will be added in future release. I cannot comment on when exactly though.
