### ISSUE TITLE
Unable to Login

### ISSUE THREAD

**Issue by himanshuamodwala** [FaisalUmair/udemy-downloader-gui#95]
Was working till morning today, now all of sudden it gives Incorrect Username/Password. Tried changing the password several time but every time got the same above error

**Comment by omag0** [comment]
Same problem here.

**Comment by mohilles** [comment]
+

**Comment by Bionic31** [comment]
Same here unable 
Please fix it bro

**Comment by sabsab22** [comment]
Same problem here.

**Comment by LauretsDev** [comment]
+1

**Comment by mahdisky** [comment]
1+

**Comment by drsh0** [comment]
+1
Linux appimage

**Comment by avj2352** [comment]
+1 Windows 7 (x64) too

**Comment by Tiancheng-Luo** [comment]
I think the problem is in udemy api

**Comment by combeysamuel** [comment]
+1

**Comment by FaisalUmair** [comment]
Thank you all for reporting this. Let me check what is wrong and I will update you shortly.

**Comment by Bionic31** [comment]
Thank you sir 
Please can we get the version soon enough, cause I need to complete my downloads before this weekend runs off....  Don't have much time on me

**Comment by Bionic31** [comment]
Will be glad if done

**Comment by FaisalUmair** [comment]
@Bionic31 Uploading right now.

**Comment by FaisalUmair** [comment]
I have published v1.5.1. Let me know if the problem has been resolved.

**Comment by LauretsDev** [comment]
Resolved in Win 10. Thank you!

**Comment by rafayet13** [comment]
Facing Same Problem Since yesterday on my Windows 10.

**Comment by Bionic31** [comment]
Thanks is now working bro 
But you could've add to remember on it not anytime we want to access it we need input our details every time

**Comment by Bionic31** [comment]
Sir am getting error at a point of the download

**Comment by FaisalUmair** [comment]
What error are you getting? And does this happen for only a particular course?

**Comment by sureshds7** [comment]
Thanks Bro It's working

**Comment by ooamazingoo** [comment]
Hi,not working windows 8.1 Please fix it :)

**Comment by avj2352** [comment]
Thanks team ! Issue is now resolved on my laptop (Windows 7) using the latest version 1.5.1

**Comment by Bionic31** [comment]
Have fix it bro 
Thanks for the care

**Comment by User72000** [comment]
Login is not working from last 2-3 days, it is saying incorrect username/password but the username and password are working in browser and mobile app.

**Comment by supermazenizo** [comment]
I have the same issue on Windows 10.

**Comment by jigarthakkar3012** [comment]
> Thank you all for reporting this. Let me check what is wrong and I will update you shortly.
> 
> **UPDATE**
> 
> I have identified the cause of this issue and fixed the same. I will soon push the new version and let you know.
> 
> **For those who want to know what the issue was**, actually Udemy has made a slight change in their authentication process where they now have started to check for the origin of the request found in the `origin request header`. I have the now added the origin header to the login request and hardcoded the same to `https://www.udemy.com`

Please help to resolve this login issue. I am also unable to login the udemy downloader.

**Comment by jigarthakkar3012** [comment]
![image](https://user-images.githubusercontent.com/18280388/55238873-88ac3700-525b-11e9-90e2-21270cb22a3f.png)
