### ISSUE TITLE
Login Issues

### ISSUE THREAD

**Issue by AyaskantaIBM** [FaisalUmair/udemy-downloader-gui#98]
when I entered my email and password first time it worked fine and downloaded with good speed. But after that when again i tried login its showing username/password incorrect. I am entering correct credentials.
can you help me out on this.

**Comment by avj2352** [comment]
1.5.1 was working with username and password... but now again showing "Invalid username/password"

**Comment by FaisalUmair** [comment]
I have published v1.5.2. Download and let me know if the problem has been resolved.

**Comment by avj2352** [comment]
Thanks Faisal, its working now !!

**Comment by AyaskantaIBM** [comment]
Thanks Faisal,
This 1.5.2 version is now working fine.
Thanks.
